### ISSUE TITLE
Some menu shortcuts are misdescribed or don't work on the develop branch

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-workbench#326] opened 2018-12-19 23:52 UTC
Testing 2.6.1 on the `develop` branch using Windows 10, I see that though the code for several menu shortcuts looks identical to the corresponding code in 2.6.0, the displayed shortcuts are incorrect, and at least one no longer works correctly.  

For example, `Toggle Developer Tools` (under `View`) is shown as `Ctrl+I` but is actually `Ctrl+Shift+I` (and though this works fine on 2.6.0, in 2.6.1 you can open but not close dev tools with this shortcut on Windows 10).

Another example: `Conclusion Summary View` is shown as `Ctrl+C` but is actually `Ctrl+Shift+C`.

**Comment by majurg** [comment] 2019-01-25 01:03
@johnmhoran I believe this is working as intended. `Ctrl+I` is actually `ctrl` plus CAPITAL `i`, which is `Ctrl+shfit+I` as you've stated. Similar thing for the Conclusions Summary View. 

To my knowledge, I do not know how to change the display text to lower case characters for the various SCWB specific view tasks. Additionally, I do not know if there is a way to add `shift` to the Developer tools toggle text. 

This may be an after effect from upgrading to a new electron version.

**Comment by majurg** [comment] 2019-01-25 01:04
Ill dig into this a little more, but this may be a windows-specific issue (like so many things seem to be)

**Comment by majurg** [comment] 2019-01-25 23:57
@johnmhoran Turns it this was an issue with Electron itself (see: https://github.com/electron/electron/issues/14501)

Electron was updated with #335 so the shortcuts will show up properly in the next (and subsequent) release. Additionally, the Dev Console shortcuts have been changed on Windows to make it more clear to the user. 

Closing this.

**Closed by majurg** 2019-01-25 23:57 UTC
Labels: bug
